import { InterFont } from './fonts'
import './globals.css'

export const metadata = {
  title: 'R6 Index',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ InterFont.className }>
      <body>
        {children}
      </body>
    </html>
  )
}
